name: client
description: "SSAFY 대전 캠퍼스의 학생들을 위한 셔틀 버스 앱입니다."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  flutter_naver_map: ^1.2.2+flutter3.22
  flutter_dotenv: ^5.1.0
  geolocator: ^12.0.0
  widgetbook_annotation: ^3.1.0
  pointer_interceptor: ^0.10.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  widgetbook: ^3.8.0
  widgetbook_generator: ^3.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    # - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
