name: client
description: "SSAFY 대전 캠퍼스의 학생들을 위한 셔틀 버스 앱입니다."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  flutter_naver_map: ^1.3.0+1
  flutter_dotenv: ^5.1.0
  geolocator: ^13.0.2
  web: ^1.1.0
  json_annotation: ^4.9.0
  pointer_interceptor: ^0.10.1+2
  ferry: ^0.16.1+2
  ferry_flutter: ^0.9.1+1
  gql_http_link: ^1.1.0
  ferry_hive_store: ^0.6.0+1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  ferry_generator: ^0.12.1-dev.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
