name: Build web and Deploy (Prod)

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

env:
  APP_VERSION: ${{ github.event.release.tag_name || github.event.inputs.tag }}
  HOST: ${{ vars.HOST }}

jobs:
  build-and-deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.APP_VERSION }}

      - name: Set up and build Flutter web
        uses: IsItgone/ci-templates/.github/actions/build-flutter@main
        with:
          platform: web
          map-api-key-id: ${{ secrets.NAVER_MAP_CLIENT_ID }}
          api-host: ${{ env.HOST }}

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel
        run: vercel build/web --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
