name: Build web and Deploy (Dev)

on:
  push:
    branches:
      - main
      - ci # TODO: delete
  workflow_dispatch:

env:
  ENVIRONMENT: dev
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  IMAGE_REPOSITORY: ${{ vars.REGISTRY }}/${{ vars.ORGANIZATION }}/${{ github.event.repository.name }}
  APP_VERSION: ${{ github.sha }}
  HOST: dev.${{ vars.HOST }}


jobs:
  build-and-push:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up and build Flutter web
        uses: IsItgone/ci-templates/.github/actions/build-flutter-web@main
        with:
          NAVER_MAP_CLIENT_ID: ${{ secrets.NAVER_MAP_CLIENT_ID }}
          HOST: ${{ env.HOST }}

#      # Build
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: "3.29.2"
#
#      - name: Install dependencies
#        run: flutter pub get
#
#      - name: Generate GraphQL Schema & Models
#        run: flutter pub run build_runner build --delete-conflicting-outputs
#
#      - name: Build Flutter Web
#        run: flutter build web --release --dart-define=NAVER_MAP_CLIENT_ID=${{ secrets.NAVER_MAP_CLIENT_ID }} --dart-define=API_URL=https://${{ env.HOST }}/api/graphql --base-href /

      - name: Build and Push image with Docker buildx
        if: false # TODO: delete
        uses: IsItgone/ci-templates/.github/actions/build-and-push-image@main
        with:
          registry: ${{ vars.REGISTRY }}
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ env.APP_VERSION }}
          password: ${{ secrets.GHCR_TOKEN }}


  update-helm-chart:
    if: false # TODO: delete
    needs: build-and-push
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.ORGANIZATION }}/cluster-config
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Update Helm Chart
        working-directory: apps/${{ env.REPOSITORY_NAME }}/${{ env.ENVIRONMENT }}/chart
        run: |
          yq -i '.appVersion = "${{ env.APP_VERSION }}"' Chart.yaml
          yq -i '.flutter-base.image.repository = "${{ env.IMAGE_REPOSITORY }}"' values.yaml
          yq -i '.flutter-base.image.tag = "${{ env.APP_VERSION }}"' values.yaml
          yq -i '.flutter-base.ingress.host = "${{ env.HOST }}"' values.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Image tag to ${{ env.APP_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}