name: Build web and Deploy (Prod)

on:
  release:
    types: [published]
  push: # TODO: delete
    branches:
      - ci

  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

env:
#  APP_VERSION: ${{ github.event.release.tag_name || github.event.inputs.tag }} # TODO: uncomment
  APP_VERSION: ${{ github.event.release.tag_name || github.event.inputs.tag || github.sha }} # TODO: delete
  HOST: ${{ vars.HOST }}

jobs:
  build-and-deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.APP_VERSION }}

      - name: Debug inputs & release tag # TODO: delete
        run: |
          echo "event_name        = ${{ github.event_name }}"
          echo "app version       = ${{ env.APP_VERSION }}"        

      - name: Set up and build Flutter web
        if: false # TODO: delete
        uses: IsItgone/ci-templates/.github/actions/build-flutter-web@main
        with:
          NAVER_MAP_CLIENT_ID: ${{ secrets.NAVER_MAP_CLIENT_ID }}
          HOST: ${{ env.HOST }}


      - name: Install Vercel CLI
        if: false # TODO: delete
        run: npm install -g vercel@latest

      - name: Deploy to Vercel
        if: false # TODO: delete
        run: vercel build/web --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
